development:
#  adapter: mysql2
#  encoding: utf8
#  reconnect: false
#  database: cumplo_db
#  pool: 5
#  username: root
#  password:
#  port: 3306
#  host: localhost
  adapter: sqlite3
  database: db/cumplo_dev.sqlite.db


test:
  adapter: sqlite3
  database: db/cumplo_test.sqlite.db

production:
  adapter: sqlite3
  database: db/cumplo_db.sqlite.db
